<?php
  echo "<h1>Olá Mundo v4.0</h1> ";
  echo $_SERVER['SERVER_ADDR']

  echo "<script type=\"text/javascript\">
  var a=window;a.dT_?a.console&&a.console.log(\"Duplicate agent injection detected, turning off redundant initConfig.\"):navigator.userAgent&&0<=navigator.userAgent.indexOf(\"RuxitSynthetic\")||navigator.cookieEnabled&&(window.dT_||(window.dT_={cfg:\"app=280564972A8B1342|cors=1|featureHash=A2SVfqr|lastModification=0|dtVersion=10129170927131437|reportUrl=https://bf20190olf.bf.dynatrace.com/bf|tp=500,50,0,1|featureHash=A2SVfqr|auto=false|domain=|rid=RID_|rpid=|app=280564972A8B1342\"}));(function(){function l(){var a=0;try{a=ma.performance.timing.navigationStart+Math.floor(ma.performance.now())}catch(c){}return 0>=a||isNaN(a)?(new Date).getTime():a}function na(a,c){return oa(a,c)}function g(a,c){for(var d=1;d<arguments.length;d++)a.push(arguments[d])}function pa(a){g(qa,a)}function r(a,c){return parseInt(a,c||10)}function ra(a){try{if(R)return R[a]}catch(c){}return null}function sa(a,c){try{window.sessionStorage.setItem(a,c)}catch(d){}}function f(a,c){var d=-1;c&&a&&a.indexOf&&(d=
  a.indexOf(c));return d}function ta(a){document.cookie=a+'=\"\";path=/'+(e.domain?\";domain=\"+e.domain:\"\")+\"; expires=Thu, 01 Jan 1970 00:00:01 GMT;\"}function ua(a){a=encodeURIComponent(a);var c=[];if(a)for(var d=0;d<a.length;d++){var t=a.charAt(d);g(c,$a[t]||t)}return c.join(\"\")}function D(a,c,d,t){va(function(){if(c||0===c){c=(\"\"+c).replace(/[;\n\r]/g,\"_\");c=\"DTSA\"===a.toUpperCase()?ua(c):c;var b=a+\"=\"+c+\";path=/\"+(e.domain?\";domain=\"+e.domain:\"\");d&&(b+=\";expires=\"+d.toUTCString());t&&(b+=\";Secure\");
  document.cookie=b}else ta(a)})}function n(a){var c,d,t,b=document.cookie.split(\";\");for(c=0;c<b.length;c++)if(d=f(b[c],\"=\"),t=b[c].substring(0,d),d=b[c].substring(d+1),t=t.replace(/^\s+|\s+$/g,\"\"),t===a)return\"DTSA\"===a.toUpperCase()?decodeURIComponent(d):d;return\"\"}function wa(a){var c=/^[0-9A-Za-z_\$\+\/\.\-\*%\|]*$/.test(a);return 0>=f(a,\"$\")||a&&2<a.split(\"$\").length?!1:c}function S(){var a=n(v);return a&&wa(a)?a:\"\"}function T(a){D(v,a,void 0,b.bcv(\"ssc\"))}function xa(a){a=a||S();var c={sessionId:null,
  v:null};if(a){var d=f(a,\"|\"),b=a;-1!==d&&(b=a.substring(0,d));d=f(b,\"$\");-1!==d?(c.sessionId=b.substring(d+1),c.v=b.substring(0,d)):c.sessionId=b}return c}function I(a){try{if(\"undefined\"!==typeof window.DynatraceJsBridge&&\"undefined\"!==typeof window.DynatraceJsBridge.getServerId())return window.DynatraceJsBridge.getServerId()}catch(c){}return xa(a).v}function J(a){if(a)return xa(a).sessionId;if(a=S()){var c=f(a,\"|\");-1!=c&&(a=a.substring(0,c))}return a}function w(a,c){return Math.floor(Math.random()*
  (c-a+1))+a}function K(a){var c=window.crypto||window.msCrypto,d;if(c)d=new Int8Array(a),c.getRandomValues(d);else for(d=[],c=0;c<a;c++)d.push(w(0,32));a=[];for(c=0;c<d.length;c++){var b=Math.abs(d[c]%32);a.push(String.fromCharCode(b+(9>=b?48:55)))}return a.join(\"\")}function ya(a){return document.getElementsByTagName(a)}function za(a){var c=a.length;if(\"number\"===typeof c)a=c;else{for(var c=0,d=2048;a[d-1];)c=d,d+=d;for(var b=7;1<d-c;)b=(d+c)/2,a[b-1]?c=b:d=b;a=a[b]?d:c}return a}function Aa(a){var c=
  {};a=a.split(\"|\");for(var d=0;d<a.length;d++){var b=a[d].split(\"=\");2==b.length&&(c[b[0]]=decodeURIComponent(b[1].replace(/\+/g,\" \")))}return c}function E(a,c,d){c=c||{};a=a.split(\"|\");for(var b=0;b<a.length;b++){var e=f(a[b],\"=\"),k;-1===e?(k=a[b],c[k]=\"1\"):(k=a[b].substring(0,e),c[k]=a[b].substring(e+1,a[b].length))}!d&&(d=c,a=d.spc)&&(b=document.createElement(\"textarea\"),b.innerHTML=a,d.spc=b.value);return c}function U(a){return a in e?e[a]:V[a]}function x(a){a=U(a);return\"false\"===a||\"0\"===a?!1:
  !!a}function ab(a,c){e[a]=c}function Ba(a){var c=location.hostname;return c&&a?c==a||-1!==c.indexOf(\".\"+a,c.length-(\".\"+a).length):!0}function W(a){e[a]=0>f(e[a],\"#\"+a.toUpperCase())?e[a]:\"\"}function bb(a,c){var d={};e.legacy=\"1\";if(a){var b=/([a-zA-Z]*)[0-9]{0,4}_([a-zA-Z_0-9]*)_([0-9]+)/g.exec(a);b&&b.length&&(d.csu=b[1],d.featureHash=b[2],d.agentLocation=a.substr(0,f(a,b[1])-1),d.buildNumber=b[3])}c&&E(c,d,!0);Ba(d.domain)||(delete d.domain,d.domainOverride=location.hostname+\",\"+d.domain);return d}
  function Ca(a){var c=a.agentUri;c&&-1<f(c,\"_\")&&(c=/([a-zA-Z]*)[0-9]{0,4}_([a-zA-Z_0-9]*)_[0-9]+/g.exec(c),a.csu=c[1],a.featureHash=c[2])}function Da(a){a.bp=a.bp||V.bp;a.bp2&&(a.bp=2);Ba(e.domain)||(e.domainOverride=location.hostname+\",\"+e.domain,delete e.domain)}function L(a){var c=document.cookie?document.cookie.split(a).length-1:0;if(1<c){var d=e.domain||window.location.hostname,b=window.location.hostname,p=window.location.pathname,k=0,g=0;y.push(a);do{var h=b.substr(k);if(h!=d||\"/\"!==p){var f=
  a,l=h==d?null:h,r=p,n=1,m=0;do document.cookie=f+'=\"\"'+(l?\";domain=\"+l:\"\")+\";path=\"+r.substr(0,n)+\"; expires=Thu, 01 Jan 1970 00:00:01 GMT;\",n=r.indexOf(\"/\",n),m++;while(-1!=n&&5>m);f=document.cookie?document.cookie.split(a).length-1:0;f<c&&(y.push(h),c=f)}k=b.indexOf(\".\",k)+1;g++}while(0!=k&&10>g&&1<c)}}function Ea(a,c){var d=document.createElement(\"script\");d.setAttribute(\"src\",a);c&&d.setAttribute(\"defer\",\"true\");d.setAttribute(\"crossorigin\",\"anonymous\");var b=document.getElementsByTagName(\"script\")[0];
  b.parentElement.insertBefore(d,b)}function Fa(a){return M+\"/\"+z+\"_\"+a+\"_\"+(e.buildNumber||b.version)+\".js\"}function cb(){if(document.currentScript){var a=document.currentScript.src;if(a)for(var c=-1==f(a,\"_bs\")&&-1==f(a,\"_bootstrap\")&&-1==f(a,\"_complete\")?1:2,d=a.lastIndexOf(\"/\"),b=0;b<c&&-1!=d;b++)a=a.substr(0,d),d=a.lastIndexOf(\"/\");return a}return null}function Ga(){var a=n(\"rxVisitor\");if(!a||\"\"==a||a.length&&45!=a.length)a=ra(\"rxVisitor\"),a&&45==a.length||(Ha=!0,a=l()+\"\",a+=K(45-a.length));var c=
  a,d=new Date;d.setFullYear(d.getFullYear()+2);D(\"rxVisitor\",c,d,b.bcv(\"ssc\"));sa(\"rxVisitor\",c);return a}function X(a){var c=Ia(a);c||(c=N(a,!0));Y=!1;return c}function Ia(a){return!Y&&a||null==(Z()||window.rx_visitID)?(a=O(!0))&&1<=a.length&&!(aa()<=l())?(ba(l(),!1),P(),\"sessionIDorRunIDMissing\"==a[0].visitId?null:a[0].visitId):null:null}function Ja(a){a||(a=w(1,1E6));var c=J();c||(c=-1*w(2,21)+\"$\"+K(32),T(c),c=J(c));a=\"\"+a;for(var d=a.length,b=[],e=0;e<c.length;e++)b[e]=String.fromCharCode(65+Math.abs((c.charCodeAt(e)^
  a.charCodeAt(e%d))%26));return b.join(\"\")}function ca(a){var c=O(!1);da(c,a);ba(l(),!0);P()}function N(a,c){c&&(ea=!0);var d;a:{if(Y||!a||Z())if(d=Z()||window.rx_visitID){window.rx_visitID=null;break a}d=null}var b=l();d||(d=Ja(b));ca(d);return d}function Z(){return b.rx_visitID||e.rx_visitID}function P(){fa&&clearTimeout(fa);fa=na(Ka,aa()-l())}function Ka(){if(aa()<=l()&&!x(\"coo\")){var a=Ja(l());ca(a);return!0}P();return!1}function ba(a,c){var d=La().j;c&&(d=a);D(\"rxvt\",a+Ma+\"|\"+d,void 0,b.bcv(\"ssc\"))}
  function La(){var a={m:0,j:0},c=n(\"rxvt\");if(c)try{var d=c.split(\"|\");2==d.length&&(a.m=parseInt(d[0],10),a.j=parseInt(d[1],10))}catch(t){}return a}function aa(){var a=La();return Math.min(a.m,a.j+Na)}function Oa(a,c){for(var d=O(c),b=!1,e=0;e<d.length;e++)d[e].frameId===A&&(d[e].b=a,b=!0);b||g(d,{frameId:A,b:a});da(d)}function da(a,c){var d=\"\",e=!1;if(a){for(var d=[],f=0;f<a.length;f++)\"-\"!=a[f].b&&(e=!0,0<f&&0<d.length&&g(d,\"p\"),g(d,m),g(d,\"$\"),g(d,a[f].frameId),g(d,\"h\"),g(d,a[f].b));d.length||
  (F&&(N(!1,!0),F=!1),m=I(),g(d,m),g(d,\"$\"),g(d,A),g(d,\"h-\"));g(d,\"v\");g(d,c||X(e));d=d.join(\"\")}d||(F&&(N(!1,!0),F=!1),m=I(),d=m+\"$\"+A+\"h-v\"+(c||X(!1)));e=d;try{\"undefined\"!==typeof window.DynatraceJsBridge&&\"undefined\"!==typeof window.DynatraceJsBridge.setDtPc&&window.DynatraceJsBridge.setDtPc(e)}catch(k){}D(G,e,void 0,b.bcv(\"ssc\"))}function O(a){var c=n(G),b=[];if(c&&\"-\"!==c)for(var c=c.split(\"p\"),e=0;e<c.length;e++){var p=c[e].split(\"h\");if(2===p.length&&p[0]&&p[1]){var k=p[0],m;k&&0<=f(k,\"$\")&&
  (k=k.split(\"$\")[1]);if(0<=f(p[1],\"v\")){var h=p[1].split(\"v\");2==h.length&&(m=h[1],p[1]=h[0])}if(!(h=a)){var h=r(k.split(\"_\")[0]),q=l()%6E8;q<h&&(q+=6E8);h=h+9E5>q}h&&g(b,{frameId:k,b:p[1]})}}for(e=0;e<b.length;e++)b[e].visitId=m;return b}function ga(a){x(\"coo\")&&!x(\"cooO\")?(B||(B=[]),g(B,a)):a()}function va(a){if(!x(\"coo\")||x(\"cooO\"))return a()}var C=window;if(!C.dT_||!C.dT_.cfg||\"string\"!=typeof C.dT_.cfg||C.dT_.initialized)C.console&&C.console.log(\"Initconfig not found or agent already initialized! This is an injection issue.\");
  else if(!(navigator.userAgent&&0<=navigator.userAgent.indexOf(\"RuxitSynthetic\"))&&navigator.cookieEnabled){var oa=window.setTimeout,R=window.sessionStorage,b={version:\"10129170927131437\",cfg:window.dT_&&window.dT_.cfg,ica:1};window.dT_=b;var ma=window,qa=[];b.agentStartTime=l();b.nw=l;b.apush=g;b.st=na;b.aBPSL=pa;b.gBPSL=function(){return qa};b.buildType=\"appmon\";b.buildType=\"dynatrace\";var $a={\"!\":\"%21\",\"~\":\"%7E\",\"*\":\"%2A\",\"(\":\"%28\",\")\":\"%29\",\"'\":\"%27\",$:\"%24\",\";\":\"%3B\",\",\":\"%2C\"};b.gSSV=ra;b.sSSV=
  sa;b.pn=r;b.iVSC=wa;b.io=f;b.dC=ta;b.sC=D;b.esc=ua;b.gSId=I;b.gDtc=J;b.gSC=S;b.sSC=T;b.gC=n;b.cRN=w;b.cRS=K;b.gEL=za;b.gEBTN=ya;var V={ade:\"\",app:\"\",bandwidth:\"300\",bp1:!1,bp2:!1,bp:1,bs:!1,coo:!1,cooO:!1,cors:!1,csu:\"\",cux:!1,disableCookieManager:!1,disableLogging:!1,disableXhrFailures:!1,domain:\"\",domainOverride:\"\",doNotDetect:\"\",dsndb:!1,dsss:!1,euf:!1,evl:\"\",extblacklist:\"\",exteventsoff:!1,fa:!1,featureHash:\"\",ffi:!1,hvt:216E5,ign:\"\",instr:\"\",lab:!1,legacy:!1,lmut:!0,md:\"\",mdn:5E3,mepp:10,moa:30,
  mrt:3,msl:3E4,ncw:!1,ntd:!1,oat:180,ote:!1,pui:!1,reportUrl:\"\",rid:\"\",ridPath:\"\",rpid:\"\",rt:1E4,rtl:0,rtp:2,rtt:1E3,rtu:200,sl:100,sosi:!1,spc:\"\",spl:!1,ssc:!1,st:3E3,svNB:!1,tp:\"500,50,3\",tvc:3E3,uam:!1,useNewCookies:!1,WST:!1,xb:\"\",xbp:null,xmut:!0,xt:0},e={reportUrl:\"dynaTraceMonitor\",initializedModules:\"\",csu:\"dtagent\",dataDtConfig:b.cfg},db={childList:!0,subtree:!0,attributes:!0,attributeOldValue:!0},eb=[\"_DT_RENDERING_\"],ha;try{ha=window.localStorage}catch(a){}(function(){var a=e.dataDtConfig;
  \"string\"==typeof a&&-1==f(a,\"#CONFIGSTRING\")&&(E(a,e),W(\"domain\"),W(\"auto\"),W(\"app\"),Ca(e))})();var Pa=ya(\"script\"),Qa=za(Pa),q,u;if(0<Qa)for(var H,Ra=e.csu+\"_bootstrap.js\",ia=0;ia<Qa;ia++)if(H=Pa[ia],H.attributes){var Sa=H.attributes.getNamedItem(\"data-dtconfig\"),Q=H.src;if(Sa)if(u=bb(H.src,Sa.value),!q)q=u;else if(\"1\"!=u.syntheticConfig){q=u;break}var ja=Q&&Q.indexOf(Ra);if(ja&&0<=ja){var Ta=ja+Ra.length+5;u||(u=e);u.app=Q.length>Ta?Q.substr(Ta):\"Default%20Application\"}}if(q)for(var ka in q)q.hasOwnProperty(ka)&&
  (e[ka]=q[ka]);e.rx_visitID&&(b.rx_visitID=e.rx_visitID);(function(){var a=e.csu,a=(a.indexOf(\"dbg\")==a.length-3?a.substr(0,a.length-3):a)+\"_\"+e.app+\"_Store\";try{var c=ha&&ha.getItem(a);if(c){var b=Aa(c),f=E(b.config,b).lastModification||\"\",g=e.lastModification||\"\",k=r(f.substr(0,13)),l=r(g.substr(0,13));if(!g||k>=l)for(var h in b)b.hasOwnProperty(h)&&(\"config\"==h?E(b[h],e):e[h]=b[h])}}catch(fb){}})();Da(e);try{var Ua=e.ign;if(Ua&&(new RegExp(Ua)).test(window.location.href)){document.dT_=window.dT_=
  null;return}}catch(a){}var G=\"dtPC\",v=\"dtCookie\",Va=\"x-dtpc\",Wa=\"x-dtreferer\",la=\"dtLatC\";e.useNewCookies&&(G=\"rxpc\",v=\"rxsession\",la=\"rxlatency\",Va=\"x-rxpc\",Wa=\"x-rxreferer\");b.gSCN=function(){return v};b.gPCHN=function(){return Va};b.gRHN=function(){return Wa};b.pageContextCookieName=G;b.latencyCookieName=la;b.mobileSessionIDCookieName=\"dtAdk\";b.cfg=e;b.pCfg=Aa;b.pCSAA=E;b.cFHFAU=Ca;b.sCD=Da;b.bcv=x;b.ncv=function(a){var b=r(U(a));isNaN(b)&&(b=r(V[a]));return b};b.scv=function(a){return String(U(a))};
  b.stcv=ab;b.rplC=function(a){return e=a};var y=[];L(G);L(v);L(la);L(\"rxvt\");pa(function(a,b){0<y.length&&!b&&(a.a(\"dCN\",\"duplicateCookieNames\",function(){return y.join(\",\")},function(){return y.slice()}),y=[])});var A=b.agentStartTime%6E8+\"_\"+r(w(0,1E3));b.gFId=function(){return A};b.frameId=A;var Xa,M,z;try{Xa=R.getItem(\"dtDisabled\")}catch(a){}(M=e.agentLocation)||(M=cb());z=e.agentname||e.csu||\"dtagent\";z=\"ruxitagentjs\";z=n(\"dtUseDebugAgent\")?e.debugName||z+\"dbg\":e.name||z;if(!e.auto&&!e.legacy&&
  !Xa){var Ya=e.agentUri||Fa(e.featureHash);e.async?Ea(Ya,e.async):document.write('<script type=\"text/javascript\" src=\"'+Ya+'\">\x3c/script>')}if(-1!=f(window.location.href,\"_DT_RENDERING_\")){var Za=b.RMOD={};M&&(Za.conf=db,Za.ignore=eb,Ea(Fa(\"R\"),!0))}var m;ga(function(){J()||T(-1*w(2,21)+\"$\"+K(32));m=I()});b.gcSId=function(){return m};var Ha=!1;ga(Ga);b.iNV=function(){return Ha};b.gVID=Ga;var fa,Ma=18E5,Na=216E5,Y=!0,ea=!1,F=!1;if(e.hvt)try{Na=parseInt(e.hvt,10)}catch(a){}b.sVIdUP=function(){F=!0};
  b.sVTT=function(a){Ma=a};b.sVIDP=\"rx_visitID\";b.sVID=ca;b.rVID=Ia;b.gVI=X;b.gNVId=N;b.gARnVF=function(){var a=ea;ea=!1;return a};b.cAUV=function(){Ka()||(ba(l(),!1),P())};Oa(1);b.gPC=O;b.cPC=Oa;b.sPC=da;var B;n(v)&&(e.cooO=1);b.eWE=ga;b.oEIE=va;b.eA=function(){for(var a=0;a<B.length;a++)oa(B[a],0);B=[];e.cooO=1}}})();
  </script>";
?>
